// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBslXpNXBuEQEgHjVO4Fk5VZfHQfcZAnIc',
    appId: '1:668851014017:web:45fb4ad847c11953210080',
    messagingSenderId: '668851014017',
    projectId: 'flutter-new-auth',
    authDomain: 'flutter-new-auth.firebaseapp.com',
    storageBucket: 'flutter-new-auth.appspot.com',
    measurementId: 'G-G4QB6F30Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzuMPTcDQidyO2p-3FMJ6G6mkZBFvIKnE',
    appId: '1:668851014017:android:f9c4139167dbbeb6210080',
    messagingSenderId: '668851014017',
    projectId: 'flutter-new-auth',
    storageBucket: 'flutter-new-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACb5U_s82nCHLoZ9EOztXwEnPizNX91vw',
    appId: '1:668851014017:ios:878fbe3e9296c7b6210080',
    messagingSenderId: '668851014017',
    projectId: 'flutter-new-auth',
    storageBucket: 'flutter-new-auth.appspot.com',
    iosClientId: '668851014017-3al0nkupvlu1va80i6dkqcfu789rkrh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4logintuyotrial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACb5U_s82nCHLoZ9EOztXwEnPizNX91vw',
    appId: '1:668851014017:ios:878fbe3e9296c7b6210080',
    messagingSenderId: '668851014017',
    projectId: 'flutter-new-auth',
    storageBucket: 'flutter-new-auth.appspot.com',
    iosClientId: '668851014017-3al0nkupvlu1va80i6dkqcfu789rkrh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4logintuyotrial',
  );
}
